# -*- coding: utf-8 -*-
"""ml_agent_pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-euXeVESFub4LY--tJDroaX6cVlr8wi3
"""

# ============================================================
#  ML AGENT PRO — Agente Inteligente de Machine Learning
#  Ejecutar con: streamlit run ml_agent_pro.py
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold, learning_curve
)
from sklearn.preprocessing import StandardScaler, LabelEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report,
    confusion_matrix, roc_curve, auc, precision_recall_curve
)
from sklearn.feature_selection import mutual_info_classif, VarianceThreshold
import lightgbm as lgb
import optuna
from optuna.samplers import TPESampler
import shap
import lime.lime_tabular
import joblib
import io, base64, warnings, time, requests, json
from scipy import stats

warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)

# ── Configuración de página ──────────────────────────────────
st.set_page_config(
    page_title="ML Agent Pro",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Paleta de colores ────────────────────────────────────────
C_BG      = "#0B0F19"
C_CARD    = "#131A2B"
C_ACCENT  = "#10B981"
C_ACCENT2 = "#F59E0B"
C_TEXT    = "#E2E8F0"
C_MUTED   = "#64748B"
C_DANGER  = "#EF4444"
C_BORDER  = "#1E293B"

# ── CSS personalizado ────────────────────────────────────────
st.markdown(f"""
<style>
    :root {{
        --accent: {C_ACCENT};
        --card: {C_CARD};
        --border: {C_BORDER};
    }}

    /* Fondo principal y texto */
    .stApp {{
        background-color: {C_BG} !important;
        color: {C_TEXT} !important;
    }}

    /* Sidebar */
    section[data-testid="stSidebar"] {{
        background: linear-gradient(180deg, #0D1321 0%, #111827 100%) !important;
        border-right: 1px solid {C_BORDER} !important;
    }}
    .stSidebar .stMarkdown, .stSidebar label, .stSidebar span, .stSidebar p {{
        color: {C_TEXT} !important;
    }}

    /* Títulos */
    h1, h2, h3, h4, h5, h6 {{
        color: {C_TEXT} !important;
        font-family: 'Segoe UI', sans-serif !important;
    }}
    p, li, .stMarkdown, label, .interpretacion {{
        color: {C_TEXT} !important;
    }}

    /* =========================================
       SOLUCIÓN DEFINITIVA PARA TABLAS BLANCAS
       ========================================= */

    /* Contenedor principal del DataFrame */
    [data-testid="stDataFrameContainer"],
    [data-testid="stDataFrame"],
    div[data-testid="stDataFrameContainer"] {{
        background-color: transparent !important;
    }}

    /* Forzar tabla interna y celdas a oscuro */
    .stDataFrame table,
    .stDataFrame thead,
    .stDataFrame tbody,
    .stDataFrame th,
    .stDataFrame td,
    div[data-testid="stDataFrameContainer"] table,
    div[data-testid="stDataFrameContainer"] thead,
    div[data-testid="stDataFrameContainer"] tbody,
    div[data-testid="stDataFrameContainer"] th,
    div[data-testid="stDataFrameContainer"] td {{
        background-color: {C_CARD} !important;
        color: {C_TEXT} !important;
        border-color: {C_BORDER} !important;
        border-bottom: 1px solid {C_BORDER} !important;
    }}

    /* Encabezados de la tabla */
    .stDataFrame th, div[data-testid="stDataFrameContainer"] th {{
        background-color: #1A2332 !important;
        color: {C_ACCENT} !important;
        font-weight: 600 !important;
    }}

    /* Filas al pasar el mouse */
    .stDataFrame tr:hover td, div[data-testid="stDataFrameContainer"] tr:hover td {{
        background-color: #1A233222 !important;
    }}

    /* Quitar bordes blancos residuales del contenedor de Streamlit */
    .stElementContainer {{
        border: none !important;
        box-shadow: none !important;
    }}
    div[data-testid="stElementContainer"] {{
        background-color: transparent !important;
    }}

    /* Tablas generadas con Markdown */
    .stMarkdown table {{
        background-color: {C_CARD} !important;
        color: {C_TEXT} !important;
        border-color: {C_BORDER} !important;
        border-collapse: collapse !important;
    }}
    .stMarkdown th {{
        background-color: #1A2332 !important;
        color: {C_ACCENT} !important;
        border: 1px solid {C_BORDER} !important;
    }}
    .stMarkdown td {{
        background-color: {C_CARD} !important;
        color: {C_TEXT} !important;
        border: 1px solid {C_BORDER} !important;
    }}

    /* Bloques de código (st.code) */
    [data-testid="stCodeBlock"] {{
        background-color: #0B0F19 !important;
        border: 1px solid {C_BORDER} !important;
        border-radius: 8px !important;
    }}
    [data-testid="stCodeBlock"] code, [data-testid="stCodeBlock"] pre {{
        background-color: transparent !important;
        color: #E2E8F0 !important;
    }}

    /* =========================================
       ESTILOS DE TARJETAS Y COMPONENTES
       ========================================= */
    .card {{
        background: {C_CARD};
        border: 1px solid {C_BORDER};
        border-radius: 12px;
        padding: 24px;
        margin-bottom: 16px;
    }}
    .card-accent {{
        background: linear-gradient(135deg, {C_CARD} 0%, #0F2027 100%);
        border: 1px solid {C_ACCENT}33;
        border-left: 4px solid {C_ACCENT};
        border-radius: 12px;
        padding: 24px;
        margin-bottom: 16px;
    }}
    .interpretacion {{
        background: linear-gradient(135deg, #1A1A2E, #16213E);
        border-left: 4px solid {C_ACCENT2};
        border-radius: 8px;
        padding: 16px 20px;
        margin: 12px 0;
        font-size: 0.95rem;
        line-height: 1.6;
        color: {C_TEXT};
    }}
    .interpretacion strong {{ color: {C_ACCENT2}; }}

    /* Barra de progreso */
    .progress-bar {{
        display: flex;
        gap: 4px;
        margin: 16px 0;
    }}
    .progress-step {{
        flex: 1;
        height: 6px;
        border-radius: 3px;
        background: {C_BORDER};
        transition: background 0.3s;
    }}
    .progress-step.active {{
        background: {C_ACCENT};
        box-shadow: 0 0 8px {C_ACCENT}66;
    }}
    .progress-step.done {{
        background: {C_ACCENT}88;
    }}

    /* Botón de descarga */
    .stDownloadButton > button {{
        background: linear-gradient(135deg, {C_ACCENT}, #059669) !important;
        border: none !important;
        color: white !important;
        font-weight: 600 !important;
        padding: 10px 24px !important;
        border-radius: 8px !important;
    }}

    /* Scrollbar */
    ::-webkit-scrollbar {{ width: 8px; }}
    ::-webkit-scrollbar-track {{ background: {C_BG}; }}
    ::-webkit-scrollbar-thumb {{ background: {C_BORDER}; border-radius: 4px; }}
</style>
""", unsafe_allow_html=True)

# ── Configuración OpenRouter ─────────────────────────────────
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_TOKEN = "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"
OPENROUTER_MODEL = "openrouter/free"

def llm_agent_analyze(prompt):
    headers = {
        "Authorization": f"Bearer {OPENROUTER_TOKEN}",
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:8501", 
    }
    data = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {"role": "system", "content": "Eres un Data Scientist Experto llamado ML Agent Pro. Hablas en español claro y conciso para sugerir decisiones al usuario sobre sus datos."},
            {"role": "user", "content": prompt}
        ]
    }
    try:
        response = requests.post(OPENROUTER_URL, headers=headers, json=data)
        if response.status_code == 200:
            return response.json()["choices"][0]["message"]["content"]
        else:
            return f"Error en API OpenRouter: {response.text}"
    except Exception as e:
        return f"Excepción de conexión con el Agente: {str(e)}"

# ── Funciones auxiliares ─────────────────────────────────────
PASOS = [
    "Bienvenida",
    "Carga de Datos",
    "Diccionario de Datos",
    "EDA Completo",
    "Datos Faltantes",
    "Selección de Variables",
    "División Train/Test",
    "Modelos Base",
    "Optimización OPTUNA",
    "Ajuste de Thresholds",
    "Análisis Overfitting",
    "Explicabilidad SHAP/LIME",
    "Descarga del Modelo",
]

def progress_html(step_idx):
    done = step_idx
    html = '<div class="progress-bar">'
    for i in range(len(PASOS) - 1):
        cls = "done" if i < done else ("active" if i == done else "")
        html += f'<div class="progress-step {cls}"></div>'
    html += "</div>"
    return html

def safe_fig(fig, figsize=(10, 5)):
    """Asegura que la figura se cierre correctamente para Streamlit."""
    if fig is None:
        fig, ax = plt.subplots(figsize=figsize)
    return fig

def interpretar_distribucion(series, nombre):
    """Genera interpretación automática de una distribución."""
    texto = []
    skew = series.skew()
    kurt = series.kurtosis()
    texto.append(f"La variable <strong>{nombre}</strong> presenta una asimetría de {skew:.2f}")
    if abs(skew) > 1:
        texto.append("indicando una distribución fuertemente sesgada" +
                     (" hacia la derecha (cola larga positiva)" if skew > 0 else " hacia la izquierda"))
    elif abs(skew) > 0.5:
        texto.append("con un sesgo moderado")
    else:
        texto.append("con una distribución aproximadamente simétrica")
    if kurt > 3:
        texto.append(f". La curtosis de {kurt:.2f} sugiere colas pesadas (presencia de valores atípicos)")
    elif kurt < -1:
        texto.append(f". La curtosis de {kurt:.2f} indica una distribución platicúrtica (más plana de lo normal)")
    texto.append(f". Rango: [{series.min():.2f}, {series.max():.2f}], Media: {series.mean():.2f}, Mediana: {series.median():.2f}")
    return " ".join(texto) + "."

def interpretar_correlacion(corr_matrix, umbral=0.7):
    """Detecta y describe correlaciones altas."""
    pares = []
    cols = corr_matrix.columns
    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            v = corr_matrix.iloc[i, j]
            if abs(v) >= umbral:
                pares.append((cols[i], cols[j], v))
    if not pares:
        return "No se detectaron correlaciones altas (|r| >= 0.7) entre las variables numéricas. Las variables parecen ser independientes entre sí, lo cual es favorable para los modelos de clasificación."
    texto = f"Se detectaron <strong>{len(pares)} par(es)</strong> con correlación alta (|r| >= 0.7): "
    for a, b, v in pares:
        tipo = "positiva" if v > 0 else "negativa"
        texto += f"<strong>{a}</strong> y <strong>{b}</strong> (r={v:.2f}, {tipo}); "
    texto += "Estas correlaciones pueden indicar redundancia. Considere eliminar una variable de cada par para evitar multicolinealidad."
    return texto

def interpretar_resultados(resultados_df):
    """Interpretación automática de la tabla de resultados."""
    if resultados_df.empty:
        return ""
    mejor = resultados_df.loc[resultados_df["Accuracy CV Mean"].idxmax()]
    peor = resultados_df.loc[resultados_df["Accuracy CV Mean"].idxmin()]
    texto = f"""
    <div class="interpretacion">
    <strong>Interpretación automática de resultados:</strong><br><br>
    El modelo con mejor desempeño es <strong>{mejor['Modelo']}</strong> con un Accuracy medio de
    <strong>{mejor['Accuracy CV Mean']:.4f}</strong> y F1 medio de <strong>{mejor['F1 CV Mean']:.4f}</strong>.<br><br>
    El modelo con menor desempeño es <strong>{peor['Modelo']}</strong> con Accuracy de
    <strong>{peor['Accuracy CV Mean']:.4f}</strong>.<br><br>
    """
    rango = resultados_df["Accuracy CV Mean"].max() - resultados_df["Accuracy CV Mean"].min()
    if rango < 0.03:
        texto += "La diferencia entre modelos es mínima (< 3%), lo que sugiere que todos capturan patrones similares. "
        texto += "En este caso, el modelo más simple (probablemente Decision Tree) podría ser preferido por interpretabilidad."
    elif rango < 0.10:
        texto += f"Existe una diferencia moderada de {rango:.2%} entre el mejor y peor modelo. "
        texto += f"Se recomienda <strong>{mejor['Modelo']}</strong> como candidato principal para optimización."
    else:
        texto += f"La diferencia de {rango:.2%} es significativa, indicando que algunos modelos no logran capturar la estructura de los datos. "
        texto += f"<strong>{mejor['Modelo']}</strong> muestra una clara ventaja y debe ser priorizado."
    # Desbalance entre accuracy y F1
    for _, row in resultados_df.iterrows():
        diff = row["Accuracy CV Mean"] - row["F1 CV Mean"]
        if diff > 0.05:
            texto += f"<br><br>⚠️ <strong>{row['Modelo']}</strong> muestra una brecha Accuracy-F1 de {diff:.2%}, "
            texto += "lo que puede indicar desbalance de clases o predicción sesgada hacia la clase mayoritaria."
    texto += "</div>"
    return texto

def style_df(df):
    """Aplica estilo oscuro a un DataFrame de pandas."""
    return df.style.set_properties(**{
        "background-color": C_CARD,
        "color": C_TEXT,
        "border-color": C_BORDER,
        "font-size": "0.9rem",
        "padding": "8px",
    }).set_table_styles([
        {"selector": "th", "props": "background-color: #1A2332; color: #10B981; font-weight: 600;"}
    ])

# ── Inicialización de session_state ──────────────────────────
defaults = {
    "step": 0, "df": None, "df_clean": None, "target_col": None,
    "num_cols": [], "cat_cols": [], "drop_cols": [],
    "X_train": None, "X_test": None, "y_train": None, "y_test": None,
    "preprocessor": None, "base_results": None,
    "best_model_name": None, "best_pipeline": None,
    "optuna_study": None, "optuna_model": None,
    "optuna_params": None, "optimized_pipeline": None,
    "threshold": 0.5, "shap_values": None,
    "lime_explainer": None, "label_encoder": None,
    "metadata_txt": None,
}
for k, v in defaults.items():
    if k not in st.session_state:
        st.session_state[k] = v

def reset_all():
    for k, v in defaults.items():
        st.session_state[k] = v

# ── Sidebar ──────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🤖 ML Agent Pro")
    st.caption("Agente inteligente de Machine Learning")
    st.markdown("---")

    paso = st.selectbox(
        "Navegar a paso:",
        range(len(PASOS)),
        format_func=lambda i: f"{'✅' if i < st.session_state.step else '🔵' if i == st.session_state.step else '⬜'} {PASOS[i]}",
        index=st.session_state.step,
    )
    st.session_state.step = paso

    st.markdown("---")
    if st.button("🔄 Reiniciar todo", use_container_width=True):
        reset_all()
        st.rerun()

    if st.session_state.df is not None:
        st.markdown("---")
        st.caption("Resumen del dataset")
        st.metric("Filas", f"{st.session_state.df.shape[0]:,}")
        st.metric("Columnas", st.session_state.df.shape[1])
        if st.session_state.target_col:
            st.metric("Target", st.session_state.target_col)

st.markdown(progress_html(st.session_state.step), unsafe_allow_html=True)
st.markdown(f"<h2 style='margin-top:8px'>{PASOS[paso]}</h2>", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
# PASO 0: BIENVENIDA
# ══════════════════════════════════════════════════════════════
if paso == 0:
    st.markdown("""
    <div class="card-accent">
    <h2 style='color:#10B981;margin-top:0'>🤖 Bienvenido a ML Agent Pro</h2>
    <p style='font-size:1.05rem;line-height:1.8;color:#CBD5E1'>
    Este agente automatiza el ciclo completo de Machine Learning para problemas de
    <strong style='color:#10B981'>clasificación</strong>. El pipeline incluye:</p>
    <div style='display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px'>
        <div style='background:#0B0F19;padding:14px;border-radius:8px;border:1px solid #1E293B'>
            <strong style='color:#10B981'>01</strong> — Carga y exploración del dataset<br>
            <strong style='color:#10B981'>02</strong> — Diccionario de datos automático<br>
            <strong style='color:#10B981'>03</strong> — Análisis Exploratorio (EDA)<br>
            <strong style='color:#10B981'>04</strong> — Imputación de datos faltantes<br>
            <strong style='color:#10B981'>05</strong> — Selección de variables<br>
            <strong style='color:#10B981'>06</strong> — División Train/Test (70/30)<br>
        </div>
        <div style='background:#0B0F19;padding:14px;border-radius:8px;border:1px solid #1E293B'>
            <strong style='color:#F59E0B'>07</strong> — 5 modelos de clasificación<br>
            <strong style='color:#F59E0B'>08</strong> — Optimización con OPTUNA<br>
            <strong style='color:#F59E0B'>09</strong> — Ajuste de thresholds<br>
            <strong style='color:#F59E0B'>10</strong> — Análisis de overfitting<br>
            <strong style='color:#F59E0B'>11</strong> — SHAP global + LIME local<br>
            <strong style='color:#F59E0B'>12</strong> — Descarga del modelo entrenado<br>
        </div>
    </div>
    <p style='margin-top:16px;color:#94A3B8'>
    Formatos soportados: <strong>CSV</strong>, <strong>Excel</strong>, <strong>Parquet</strong>.<br>
    Sube tu dataset y el agente guiará todo el proceso.
    </p>
    </div>
    """, unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
# PASO 1: CARGA DE DATOS
# ══════════════════════════════════════════════════════════════
elif paso == 1:
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("📁 Carga tu dataset")
    col1, col2 = st.columns(2)
    with col1:
        archivo = st.file_uploader(
            "Selecciona un archivo",
            type=["csv", "xlsx", "xls", "parquet"],
            help="CSV, Excel o Parquet",
        )
    with col2:
        sep = st.selectbox("Separador (CSV)", [",", ";", "\t", "|"], index=0)
        enc = st.selectbox("Codificación", ["utf-8", "latin-1", "iso-8859-1"], index=0)

    if archivo:
        try:
            if archivo.name.endswith(".csv"):
                df = pd.read_csv(archivo, sep=sep, encoding=enc)
            elif archivo.name.endswith((".xlsx", ".xls")):
                df = pd.read_excel(archivo)
            else:
                df = pd.read_parquet(archivo)

            st.session_state.df = df
            st.session_state.step = 1
            st.success(f"✅ Dataset cargado: {df.shape[0]:,} filas × {df.shape[1]} columnas")
            st.markdown("**Vista previa:**")
            st.dataframe(df.head(8), use_container_width=True, height=320)
            st.markdown("</div>", unsafe_allow_html=True)

            col_a, col_b, col_c = st.columns(3)
            with col_a:
                st.metric("Filas", f"{df.shape[0]:,}")
            with col_b:
                st.metric("Columnas", df.shape[1])
            with col_c:
                mem = df.memory_usage(deep=True).sum() / 1024**2
                st.metric("Memoria", f"{mem:.2f} MB")

            st.markdown("---")
            st.markdown("**(Opcional)** Sube un diccionario o explicación de variables para que la IA aplique contexto de negocio:")
            archivo_meta = st.file_uploader("Metadatos (CSV, TXT, MD)", type=["txt", "csv", "md"], key="f_meta")
            if archivo_meta:
                if archivo_meta.name.endswith(".csv"):
                    try:
                        st.session_state.metadata_txt = pd.read_csv(archivo_meta, sep=sep, encoding=enc).to_string()
                    except:
                        st.session_state.metadata_txt = "Error leyendo CSV de metadatos."
                else:
                    st.session_state.metadata_txt = archivo_meta.read().decode("utf-8", errors="ignore")
                st.success("✅ Metadatos de contexto cargados en memoria de la IA.")

            if st.button("Continuar al Diccionario de Datos →", type="primary", use_container_width=True):
                st.session_state.step = 2
                st.rerun()
        except Exception as e:
            st.error(f"Error al cargar: {e}")
    else:
        st.info("👆 Sube un archivo para comenzar.")
        st.markdown("</div>", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
# PASO 2: DICCIONARIO DE DATOS
# ══════════════════════════════════════════════════════════════
elif paso == 2:
    if st.session_state.df is None:
        st.warning("⚠️ Primero carga un dataset en el paso 1.")
    else:
        df = st.session_state.df.copy()
        # Clasificar variables inteligentemente
        cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
        raw_num = df.select_dtypes(include=[np.number]).columns.tolist()
        
        num_cols = []
        for col in raw_num:
            # Consideramos variables numéricas con 15 o menos valores únicos como categóricas
            if df[col].nunique() <= 15:
                cat_cols.append(col)
            else:
                num_cols.append(col)

        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("📖 Diccionario de Datos")

        col_a, col_b = st.columns(2)
        with col_a:
            st.markdown(f"**Variables Numéricas ({len(num_cols)})**")
            for c in num_cols:
                st.markdown(f"- `{c}` — min: {df[c].min():.2f}, max: {df[c].max():.2f}, media: {df[c].mean():.2f}")
        with col_b:
            st.markdown(f"**Variables Categóricas ({len(cat_cols)})**")
            for c in cat_cols:
                u = df[c].nunique()
                st.markdown(f"- `{c}` — {u} valores únicos: {df[c].unique()[:5]}{'...' if u > 5 else ''}")

        # Tabla completa del diccionario
        dict_data = []
        for c in df.columns:
            tipo = "Numérica" if c in num_cols else "Categórica"
            n_miss = df[c].isnull().sum()
            pct_miss = n_miss / len(df) * 100
            if c in num_cols:
                dict_data.append({
                    "Variable": c, "Tipo": tipo,
                    "Únicos": df[c].nunique(),
                    "Nulos": n_miss, "% Nulos": f"{pct_miss:.1f}%",
                    "Min": f"{df[c].min():.2f}", "Max": f"{df[c].max():.2f}",
                    "Media": f"{df[c].mean():.2f}",
                })
            else:
                dict_data.append({
                    "Variable": c, "Tipo": tipo,
                    "Únicos": df[c].nunique(),
                    "Nulos": n_miss, "% Nulos": f"{pct_miss:.1f}%",
                    "Min": "—", "Max": "—",
                    "Media": "—",
                })
        dict_df = pd.DataFrame(dict_data)
        st.markdown("**Tabla completa del diccionario:**")
        st.dataframe(style_df(dict_df), use_container_width=True, height=400)
        st.markdown("</div>", unsafe_allow_html=True)

        # Selección de variable objetivo
        st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
        st.subheader("🎯 Selección de Variable Objetivo (Target)")
        st.markdown("Elige la variable más importante para el estudio de clasificación:")

        # Recomendación automática
        recomendadas = []
        for c in df.columns:
            u = df[c].nunique()
            n_miss = df[c].isnull().sum() / len(df)
            if 2 <= u <= 20 and n_miss < 0.3 and c.lower() not in ["id", "index", "nombre", "name"]:
                recomendadas.append(c)
        target = st.selectbox("Variable target:", df.columns,
                              index=df.columns.get_loc(recomendadas[0]) if recomendadas else 0)
        st.session_state.target_col = target
        st.session_state.num_cols = [c for c in num_cols if c != target]
        st.session_state.cat_cols = [c for c in cat_cols if c != target]

        n_classes = df[target].nunique()
        st.info(f"Target `{target}` tiene {n_classes} clases: {df[target].value_counts().to_dict()}")
        if n_classes > 20:
            st.warning("⚠️ El target tiene muchas clases únicas. ¿Es realmente una variable de clasificación?")
        st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
        st.subheader("🤖 Análisis de IA")
        if st.button("Analizar Diccionario con el Agente", key="btn_agent_dict"):
            with st.spinner("El Agente está analizando la estructura de los datos..."):
                prompt = (
                    f"Analiza el siguiente resumen de datos y dame consejos útiles sobre qué eliminar o transformar:\n"
                    f"Target seleccionado: {target}. Clases del target: {n_classes}\n"
                    f"Resumen del diccionario de datos: \n{dict_df.to_string()}"
                )
                if st.session_state.get("metadata_txt"):
                    prompt += f"\n\nContexto extra proporcionado por el usuario sobre las variables:\n{st.session_state.metadata_txt}"
                
                respuesta = llm_agent_analyze(prompt)
                st.markdown("### 💡 Diagnóstico del Agente")
                st.info(respuesta)
        st.markdown("</div>", unsafe_allow_html=True)

        if st.button("Continuar al EDA →", type="primary", use_container_width=True):
            st.session_state.step = 3
            st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 3: EDA COMPLETO
# ══════════════════════════════════════════════════════════════
elif paso == 3:
    if st.session_state.df is None or st.session_state.target_col is None:
        st.warning("⚠️ Completa los pasos anteriores primero.")
    else:
        df = st.session_state.df
        target = st.session_state.target_col
        num_cols = st.session_state.num_cols
        cat_cols = st.session_state.cat_cols

        # ── Distribución del target ──
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("📊 Distribución de la Variable Objetivo")
        fig, ax = plt.subplots(figsize=(8, 4))
        vc = df[target].value_counts()
        colors = [C_ACCENT, C_ACCENT2, "#8B5CF6", "#EC4899", "#06B6D4"][:len(vc)]
        bars = ax.bar(vc.index.astype(str), vc.values, color=colors, edgecolor="none", width=0.6)
        for bar, val in zip(bars, vc.values):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + max(vc.values)*0.02,
                    f"{val}\n({val/len(df)*100:.1f}%)", ha="center", va="bottom",
                    fontsize=10, fontweight="bold", color=C_TEXT)
        ax.set_xlabel(target, color=C_TEXT, fontsize=11)
        ax.set_ylabel("Frecuencia", color=C_TEXT, fontsize=11)
        ax.set_facecolor(C_BG)
        fig.patch.set_facecolor(C_CARD)
        ax.tick_params(colors=C_TEXT)
        ax.spines[:].set_color(C_BORDER)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

        # Interpretación del balance
        ratio = vc.values[0] / vc.values[1] if len(vc) >= 2 else 0
        if ratio > 3:
            bal_text = f"⚠️ <strong>Desbalance severo</strong> detectado (ratio {ratio:.1f}:1). La clase mayoritaria domina. Considere usar class_weight='balanced' o técnicas de sobremuestreo (SMOTE)."
        elif ratio > 1.5:
            bal_text = f"⚡ <strong>Desbalance moderado</strong> (ratio {ratio:.1f}:1). Los modelos pueden sesgarse hacia la clase mayoritaria."
        else:
            bal_text = f"✅ <strong>Clases balanceadas</strong> (ratio {ratio:.1f}:1). No se requieren técnicas de balanceo especiales."
        st.markdown(f"<div class='interpretacion'>{bal_text}</div>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

        # ── Variables numéricas ──
        if num_cols:
            st.markdown("<div class='card'>", unsafe_allow_html=True)
            st.subheader("📈 Distribución de Variables Numéricas")
            n = len(num_cols)
            cols_per_row = min(3, n)
            rows = (n + cols_per_row - 1) // cols_per_row
            fig, axes = plt.subplots(rows, cols_per_row, figsize=(5*cols_per_row, 4*rows))
            if rows == 1 and cols_per_row == 1:
                axes = np.array([[axes]])
            elif rows == 1 or cols_per_row == 1:
                axes = axes.reshape(rows, cols_per_row)
            for idx, col in enumerate(num_cols):
                r, c = divmod(idx, cols_per_row)
                ax = axes[r][c]
                df[col].dropna().hist(bins=30, ax=ax, color=C_ACCENT, alpha=0.85, edgecolor="none")
                ax.set_title(col, color=C_TEXT, fontsize=11, fontweight="bold")
                ax.set_facecolor(C_BG)
                ax.tick_params(colors=C_MUTED, labelsize=8)
                ax.spines[:].set_color(C_BORDER)
            for idx in range(n, rows * cols_per_row):
                r, c = divmod(idx, cols_per_row)
                axes[r][c].set_visible(False)
            fig.patch.set_facecolor(C_CARD)
            plt.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

            # Interpretación por variable
            for col in num_cols:
                st.markdown(f"<div class='interpretacion'>{interpretar_distribucion(df[col].dropna(), col)}</div>",
                            unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

            # ── Boxplots por target ──
            if len(num_cols) <= 8:
                st.markdown("<div class='card'>", unsafe_allow_html=True)
                st.subheader("📦 Boxplots por Clase Target")
                cols_pr = min(3, len(num_cols))
                rows_pr = (len(num_cols) + cols_pr - 1) // cols_pr
                fig2, axes2 = plt.subplots(rows_pr, cols_pr, figsize=(5*cols_pr, 4*rows_pr))
                if rows_pr == 1 and cols_pr == 1:
                    axes2 = np.array([[axes2]])
                elif rows_pr == 1 or cols_pr == 1:
                    axes2 = axes2.reshape(rows_pr, cols_pr)
                for idx, col in enumerate(num_cols):
                    r, c = divmod(idx, cols_pr)
                    ax = axes2[r][c]
                    clases = sorted(df[target].dropna().unique())
                    datos = [df[df[target] == cl][col].dropna().values for cl in clases]
                    bp = ax.boxplot(datos, labels=[str(cl) for cl in clases],
                                    patch_artist=True, widths=0.5)
                    for patch, color in zip(bp["boxes"], [C_ACCENT, C_ACCENT2, "#8B5CF6"][:len(clases)]):
                        patch.set_facecolor(color)
                        patch.set_alpha(0.7)
                    for el in bp["whiskers"] + bp["caps"] + bp["medians"]:
                        el.set_color(C_TEXT)
                    ax.set_title(col, color=C_TEXT, fontsize=11, fontweight="bold")
                    ax.set_facecolor(C_BG)
                    ax.tick_params(colors=C_MUTED, labelsize=8)
                    ax.spines[:].set_color(C_BORDER)
                for idx in range(len(num_cols), rows_pr * cols_pr):
                    r, c = divmod(idx, cols_pr)
                    axes2[r][c].set_visible(False)
                fig2.patch.set_facecolor(C_CARD)
                plt.tight_layout()
                st.pyplot(fig2)
                plt.close(fig2)
                st.markdown("</div>", unsafe_allow_html=True)

        # ── Variables categóricas ──
        if cat_cols:
            st.markdown("<div class='card'>", unsafe_allow_html=True)
            st.subheader("🏷️ Distribución de Variables Categóricas")
            cols_pr = min(3, len(cat_cols))
            rows_pr = (len(cat_cols) + cols_pr - 1) // cols_pr
            fig3, axes3 = plt.subplots(rows_pr, cols_pr, figsize=(5*cols_pr, 4*rows_pr))
            if rows_pr == 1 and cols_pr == 1:
                axes3 = np.array([[axes3]])
            elif rows_pr == 1 or cols_pr == 1:
                axes3 = axes3.reshape(rows_pr, cols_pr)
            for idx, col in enumerate(cat_cols):
                r, c = divmod(idx, cols_pr)
                ax = axes3[r][c]
                vc_cat = df[col].value_counts().head(10)
                ax.barh(range(len(vc_cat)), vc_cat.values, color=C_ACCENT2, alpha=0.85)
                ax.set_yticks(range(len(vc_cat)))
                ax.set_yticklabels(vc_cat.index.astype(str), fontsize=8)
                ax.invert_yaxis()
                ax.set_title(col, color=C_TEXT, fontsize=11, fontweight="bold")
                ax.set_facecolor(C_BG)
                ax.tick_params(colors=C_MUTED, labelsize=8)
                ax.spines[:].set_color(C_BORDER)
            for idx in range(len(cat_cols), rows_pr * cols_pr):
                r, c = divmod(idx, cols_pr)
                axes3[r][c].set_visible(False)
            fig3.patch.set_facecolor(C_CARD)
            plt.tight_layout()
            st.pyplot(fig3)
            plt.close(fig3)
            st.markdown("</div>", unsafe_allow_html=True)

        # ── Matriz de correlación ──
        if len(num_cols) > 1:
            st.markdown("<div class='card'>", unsafe_allow_html=True)
            st.subheader("🔥 Matriz de Correlación")
            corr = df[num_cols].corr()
            fig4, ax4 = plt.subplots(figsize=(max(8, len(num_cols)*0.8), max(6, len(num_cols)*0.65)))
            mask = np.triu(np.ones_like(corr, dtype=bool), k=1)
            sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap="RdYlGn",
                        center=0, ax=ax4, linewidths=0.5, linecolor=C_BORDER,
                        annot_kws={"size": 8, "color": C_TEXT})
            ax4.set_facecolor(C_BG)
            fig4.patch.set_facecolor(C_CARD)
            ax4.tick_params(colors=C_MUTED, labelsize=9)
            plt.tight_layout()
            st.pyplot(fig4)
            plt.close(fig4)
            st.markdown(f"<div class='interpretacion'>{interpretar_correlacion(corr)}</div>",
                        unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
        st.subheader("🤖 Análisis de IA (EDA)")
        if st.button("Generar Insights del EDA", key="btn_agent_eda"):
            with st.spinner("El Agente está analizando las gráficas y correlaciones..."):
                try:
                    corr = df[num_cols].corr()
                    corr_txt = "Correlación alta:\n" + interpretar_correlacion(corr)
                except:
                    corr_txt = "No hay matriz de correlación."
                bal_txt = f"Balance del target '{target}': {df[target].value_counts().to_dict()}"
                prompt = (
                    "Actúa como un experto en Data Science. Te paso un resumen del EDA. "
                    "Explícame si el desbalance del target será un problema, qué problemas de multicolinealidad detectas dadas estas correlaciones altas:\n\n"
                    f"{bal_txt}\n\n"
                    f"{corr_txt}"
                )
                respuesta = llm_agent_analyze(prompt)
                st.markdown("### 💡 Análisis Exploratorio del Agente")
                st.info(respuesta)
        st.markdown("</div>", unsafe_allow_html=True)

        if st.button("Continuar a Datos Faltantes →", type="primary", use_container_width=True):
            st.session_state.step = 4
            st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 4: DATOS FALTANTES E IMPUTACIÓN
# ══════════════════════════════════════════════════════════════
elif paso == 4:
    if st.session_state.df is None:
        st.warning("⚠️ Completa los pasos anteriores.")
    else:
        df = st.session_state.df
        target = st.session_state.target_col
        num_cols = st.session_state.num_cols
        cat_cols = st.session_state.cat_cols

        # Análisis de faltantes
        missing = df.isnull().sum()
        missing = missing[missing > 0].sort_values(ascending=False)
        pct = (missing / len(df) * 100).round(1)

        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("🔍 Análisis de Datos Faltantes")
        if missing.empty:
            st.success("✅ No se detectaron datos faltantes en el dataset.")
            st.session_state.df_clean = df.copy()
        else:
            miss_df = pd.DataFrame({
                "Variable": missing.index,
                "Nulos": missing.values,
                "% Faltante": pct.values,
                "Tipo": ["Numérica" if c in num_cols else "Categórica" for c in missing.index],
            })
            st.dataframe(style_df(miss_df), use_container_width=True, height=300)

            # Gráfico de faltantes
            fig, ax = plt.subplots(figsize=(max(8, len(missing)*0.6), 5))
            bars = ax.barh(range(len(missing)), pct.values, color=[
                C_DANGER if v > 40 else C_ACCENT2 if v > 20 else C_ACCENT for v in pct.values
            ], edgecolor="none", height=0.6)
            ax.set_yticks(range(len(missing)))
            ax.set_yticklabels(missing.index, color=C_TEXT, fontsize=10)
            ax.invert_yaxis()
            for bar, val in zip(bars, pct.values):
                ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                        f"{val}%", va="center", color=C_TEXT, fontsize=10, fontweight="bold")
            ax.set_xlabel("% Faltante", color=C_TEXT)
            ax.set_facecolor(C_BG)
            fig.patch.set_facecolor(C_CARD)
            ax.spines[:].set_color(C_BORDER)
            ax.tick_params(colors=C_MUTED)
            plt.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

            # Interpretación
            alto = pct[pct > 40]
            medio = pct[(pct >= 20) & (pct <= 40)]
            bajo = pct[pct < 20]
            interp = f"Se encontraron <strong>{len(missing)} variables</strong> con datos faltantes. "
            if len(alto) > 0:
                interp += f"<strong>{len(alto)} variable(s)</strong> con más del 40% de faltantes ({', '.join(alto.index)}): considere eliminarlas. "
            if len(medio) > 0:
                interp += f"<strong>{len(medio)} variable(s)</strong> con 20-40% de faltantes: requieren imputación cuidadosa. "
            if len(bajo) > 0:
                interp += f"<strong>{len(bajo)} variable(s)</strong> con menos del 20%: imputación directa es viable. "
            st.markdown(f"<div class='interpretacion'>{interp}</div>", unsafe_allow_html=True)

            # Selección de estrategia
            st.markdown("**Estrategia de imputación por variable:**")
            impute_strategies = {}
            cols_to_impute = st.columns(min(4, len(missing)))
            for idx, col in enumerate(missing.index):
                with cols_to_impute[idx % len(cols_to_impute)]:
                    if col in num_cols:
                        strat = st.selectbox(f"`{col}` (Num)", ["Mediana", "Media", "KNN"], key=f"imp_{col}")
                        impute_strategies[col] = {"Mediana": "median", "Media": "mean", "KNN": "knn"}[strat]
                    else:
                        strat = st.selectbox(f"`{col}` (Cat)", ["Moda", "Constante 'Desconocido'"], key=f"imp_{col}")
                        impute_strategies[col] = "most_frequent" if "Moda" in strat else "constant_unknown"

            # Variables a eliminar por alto % de faltantes
            drop_high = [c for c in alto.index if c != target]
            st.markdown("</div>", unsafe_allow_html=True)

            st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
            st.subheader("🤖 Análisis de IA (Datos Faltantes)")
            if st.button("Analizar Nulos con el Agente", key="btn_agent_nulls"):
                with st.spinner("El Agente está evaluando la estrategia de imputación..."):
                    prompt = (
                        f"Tengo estas variables con valores nulos, en un dataset total de {len(df)} filas. "
                        f"¿Qué método de imputación sugieres para cada caso?\n"
                        f"{miss_df.to_string()}"
                    )
                    respuesta = llm_agent_analyze(prompt)
                    st.markdown("### 💡 Recomendación del Agente")
                    st.info(respuesta)
            st.markdown("</div>", unsafe_allow_html=True)

            if st.button("Aplicar Imputación y Continuar →", type="primary", use_container_width=True):
                df_clean = df.copy()
                # Eliminar variables con >40% faltantes
                if drop_high:
                    df_clean = df_clean.drop(columns=drop_high)
                    st.session_state.num_cols = [c for c in st.session_state.num_cols if c not in drop_high]
                    st.session_state.cat_cols = [c for c in st.session_state.cat_cols if c not in drop_high]

                # Aplicar imputación
                for col, strat in impute_strategies.items():
                    if col in drop_high:
                        continue
                    if strat == "knn" and col in st.session_state.num_cols:
                        # Imputación KNN simple
                        from sklearn.impute import KNNImputer
                        temp_num = df_clean[st.session_state.num_cols].copy()
                        imp = KNNImputer(n_neighbors=5)
                        temp_num.iloc[:] = imp.fit_transform(temp_num)
                        df_clean[col] = temp_num[col]
                    elif strat in ["median", "mean"]:
                        val = df_clean[col].median() if strat == "median" else df_clean[col].mean()
                        df_clean[col] = df_clean[col].fillna(val)
                    elif strat == "most_frequent":
                        df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])
                    elif strat == "constant_unknown":
                        df_clean[col] = df_clean[col].fillna("Desconocido")

                st.session_state.df_clean = df_clean
                st.session_state.step = 5
                st.rerun()

        if st.session_state.df_clean is not None:
            if st.button("Continuar a Selección de Variables →", type="primary", use_container_width=True):
                st.session_state.step = 5
                st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 5: SELECCIÓN DE VARIABLES
# ══════════════════════════════════════════════════════════════
elif paso == 5:
    if st.session_state.df_clean is None:
        st.warning("⚠️ Completa la imputación primero.")
    else:
        df = st.session_state.df_clean
        target = st.session_state.target_col
        num_cols = st.session_state.num_cols
        cat_cols = st.session_state.cat_cols
        # Asegurar que las columnas existan
        num_cols = [c for c in num_cols if c in df.columns]
        cat_cols = [c for c in cat_cols if c in df.columns]

        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("✂️ Selección de Variables")

        # Variables candidatas a eliminar
        drop_candidates = []
        # Baja varianza
        for c in num_cols:
            if df[c].std() < 0.01:
                drop_candidates.append((c, "Varianza cercana a cero"))

        # Alta cardinalidad en categóricas
        for c in cat_cols:
            if df[c].nunique() > 50:
                drop_candidates.append((c, f"Alta cardinalidad ({df[c].nunique()} valores únicos)"))

        # Columnas tipo ID
        for c in df.columns:
            if c.lower() in ["id", "index", "row_id", "Unnamed: 0"] and c != target:
                if (c, "Tipo ID") not in drop_candidates:
                    drop_candidates.append((c, "Posible columna ID"))

        if drop_candidates:
            st.markdown("**Variables candidatas a eliminar automáticamente:**")
            for col, reason in drop_candidates:
                st.markdown(f"- ❌ `{col}` — {reason}")

        # Selección manual
        all_features = [c for c in df.columns if c != target]
        default_drops = [c for c, _ in drop_candidates]
        selected_drop = st.multiselect(
            "Selecciona variables a ELIMINAR del estudio:",
            all_features,
            default=default_drops,
        )
        st.session_state.drop_cols = selected_drop
        kept = [c for c in all_features if c not in selected_drop]
        kept_num = [c for c in kept if c in num_cols]
        kept_cat = [c for c in kept if c in cat_cols]
        st.session_state.num_cols = kept_num
        st.session_state.cat_cols = kept_cat

        st.info(f"Variables mantenidas: {len(kept)} ({len(kept_num)} numéricas, {len(kept_cat)} categóricas)")

        if selected_drop:
            interp = f"Se eliminarán <strong>{len(selected_drop)}</strong> variables: {', '.join(selected_drop)}. "
            interp += f"El dataset resultante tendrá <strong>{len(kept)}</strong> features para el modelado."
            st.markdown(f"<div class='interpretacion'>{interp}</div>", unsafe_allow_html=True)

        st.markdown("</div>", unsafe_allow_html=True)

        if st.button("Continuar a División Train/Test →", type="primary", use_container_width=True):
            # Aplicar eliminación
            cols_final = [target] + kept_num + kept_cat
            st.session_state.df_clean = df[cols_final].copy()
            st.session_state.step = 6
            st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 6: DIVISIÓN TRAIN/TEST
# ══════════════════════════════════════════════════════════════
elif paso == 6:
    if st.session_state.df_clean is None:
        st.warning("⚠️ Completa los pasos anteriores.")
    else:
        df = st.session_state.df_clean
        target = st.session_state.target_col
        num_cols = st.session_state.num_cols
        cat_cols = st.session_state.cat_cols

        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("✂️ División Train/Test (70/30)")

        random_state = st.number_input("Semilla aleatoria", value=42, min_value=0, max_value=9999)
        stratify = st.checkbox("Estratificar por target (recomendado)", value=True)

        if st.button("Ejecutar División", type="primary", use_container_width=True):
            # Encode target
            le = LabelEncoder()
            y = le.fit_transform(df[target])

            # Preprocessor
            num_transformer = Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ])
            cat_transformer = Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)),
            ])
            preprocessor = ColumnTransformer([
                ("num", num_transformer, num_cols),
                ("cat", cat_transformer, cat_cols),
            ])

            X = df.drop(columns=[target])
            strat = y if stratify else None
            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.30, random_state=random_state, stratify=strat
            )

            st.session_state.X_train = X_train
            st.session_state.X_test = X_test
            st.session_state.y_train = y_train
            st.session_state.y_test = y_test
            st.session_state.preprocessor = preprocessor
            st.session_state.label_encoder = le

        if st.session_state.X_train is not None:
            X_tr = st.session_state.X_train
            X_te = st.session_state.X_test
            y_tr = st.session_state.y_train
            y_te = st.session_state.y_test
            col_a, col_b, col_c, col_d = st.columns(4)
            col_a.metric("Train", f"{len(X_tr):,}", f"{len(X_tr)/len(df)*100:.0f}%")
            col_b.metric("Test", f"{len(X_te):,}", f"{len(X_te)/len(df)*100:.0f}%")
            col_c.metric("Features", len(num_cols) + len(cat_cols))
            col_d.metric("Clases", len(np.unique(y_tr)))

            # Verificar distribución
            fig, axes = plt.subplots(1, 2, figsize=(12, 4))
            for ax, data, label in [(axes[0], y_tr, "Train"), (axes[1], y_te, "Test")]:
                vc = pd.Series(data).value_counts()
                ax.bar(vc.index.astype(str), vc.values, color=[C_ACCENT, C_ACCENT2][:len(vc)], edgecolor="none")
                ax.set_title(f"Distribución {label}", color=C_TEXT, fontsize=12, fontweight="bold")
                ax.set_facecolor(C_BG)
                ax.tick_params(colors=C_MUTED)
                ax.spines[:].set_color(C_BORDER)
            fig.patch.set_facecolor(C_CARD)
            plt.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

            st.success("✅ División completada correctamente.")
            if st.button("Continuar a Modelos Base →", type="primary", use_container_width=True):
                st.session_state.step = 7
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
# PASO 7: MODELOS BASE
# ══════════════════════════════════════════════════════════════
elif paso == 7:
    if st.session_state.X_train is None:
        st.warning("⚠️ Completa la división Train/Test primero.")
    else:
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("🧠 Modelos de Clasificación — Evaluación Base")

        preprocessor = st.session_state.preprocessor
        X_train = st.session_state.X_train
        X_test = st.session_state.X_test
        y_train = st.session_state.y_train
        y_test = st.session_state.y_test
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

        modelos = {
            "Decision Tree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
            "KNN": KNeighborsClassifier(n_neighbors=5),
            "SVM": SVC(kernel="rbf", class_weight="balanced", probability=True, random_state=42),
            "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42, class_weight="balanced", n_jobs=-1),
            "LightGBM": lgb.LGBMClassifier(n_estimators=100, random_state=42, class_weight="balanced", verbose=-1, n_jobs=-1),
        }

        resultados = []
        pipelines = {}
        progress = st.progress(0, text="Iniciando entrenamiento...")
        start_time = time.time()

        for i, (nombre, modelo) in enumerate(modelos.items()):
            pipe = Pipeline([("preprocessor", preprocessor), ("model", modelo)])
            pipe.fit(X_train, y_train)
            pipelines[nombre] = pipe

            acc_cv = cross_val_score(pipe, X_train, y_train, cv=cv, scoring="accuracy").mean()
            f1_cv = cross_val_score(pipe, X_train, y_train, cv=cv, scoring="f1_weighted").mean()
            y_pred = pipe.predict(X_test)
            acc_test = accuracy_score(y_test, y_pred)
            f1_test = f1_score(y_test, y_pred, average="weighted")
            elapsed = time.time() - start_time

            resultados.append({
                "Modelo": nombre,
                "Accuracy CV Mean": round(acc_cv, 4),
                "F1 CV Mean": round(f1_cv, 4),
                "Accuracy Test": round(acc_test, 4),
                "F1 Test": round(f1_test, 4),
                "Tiempo (s)": round(elapsed, 2),
            })
            progress.progress((i + 1) / len(modelos), text=f"Entrenando {nombre}...")

        progress.empty()
        res_df = pd.DataFrame(resultados)
        st.session_state.base_results = res_df

        # Tabla de resultados
        st.markdown("**Tabla comparativa de modelos:**")
        st.dataframe(style_df(res_df), use_container_width=True, height=300)

        # Gráfico comparativo
        fig, ax = plt.subplots(figsize=(12, 5))
        x = np.arange(len(res_df))
        width = 0.2
        bars1 = ax.bar(x - 1.5*width, res_df["Accuracy CV Mean"], width, label="Accuracy CV", color=C_ACCENT, edgecolor="none")
        bars2 = ax.bar(x - 0.5*width, res_df["F1 CV Mean"], width, label="F1 CV", color=C_ACCENT2, edgecolor="none")
        bars3 = ax.bar(x + 0.5*width, res_df["Accuracy Test"], width, label="Accuracy Test", color="#8B5CF6", edgecolor="none")
        bars4 = ax.bar(x + 1.5*width, res_df["F1 Test"], width, label="F1 Test", color="#EC4899", edgecolor="none")
        for bars in [bars1, bars2, bars3, bars4]:
            for bar in bars:
                h = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2, h + 0.005, f"{h:.3f}",
                        ha="center", va="bottom", fontsize=7, color=C_TEXT, fontweight="bold")
        ax.set_xticks(x)
        ax.set_xticklabels(res_df["Modelo"], color=C_TEXT, fontsize=10)
        ax.set_ylabel("Score", color=C_TEXT)
        ax.set_facecolor(C_BG)
        fig.patch.set_facecolor(C_CARD)
        ax.legend(facecolor=C_CARD, edgecolor=C_BORDER, labelcolor=C_TEXT, fontsize=9)
        ax.spines[:].set_color(C_BORDER)
        ax.tick_params(colors=C_MUTED)
        ax.set_ylim(0, 1.15)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

        # Interpretación automática
        best_idx = res_df["Accuracy CV Mean"].idxmax()
        best_name = res_df.loc[best_idx, "Modelo"]
        st.session_state.best_model_name = best_name
        st.session_state.best_pipeline = pipelines[best_name]
        st.markdown(interpretar_resultados(res_df), unsafe_allow_html=True)

        # Matrices de confusión
        st.markdown("**Matrices de confusión:**")
        cols_mc = st.columns(min(3, len(modelos)))
        for idx, (nombre, pipe) in enumerate(pipelines.items()):
            with cols_mc[idx % len(cols_mc)]:
                y_pred = pipe.predict(X_test)
                cm = confusion_matrix(y_test, y_pred)
                fig_mc, ax_mc = plt.subplots(figsize=(4, 3.5))
                sns.heatmap(cm, annot=True, fmt="d", cmap="Greens", ax=ax_mc,
                            linewidths=0.5, linecolor=C_BORDER, annot_kws={"size": 12, "color": C_TEXT})
                ax_mc.set_title(nombre, color=C_TEXT, fontsize=10, fontweight="bold")
                ax_mc.set_facecolor(C_BG)
                fig_mc.patch.set_facecolor(C_CARD)
                ax_mc.tick_params(colors=C_MUTED)
                plt.tight_layout()
                st.pyplot(fig_mc)
                plt.close(fig_mc)

        st.markdown("</div>", unsafe_allow_html=True)

        if st.button("Continuar a Optimización OPTUNA →", type="primary", use_container_width=True):
            st.session_state.step = 8
            st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 8: OPTIMIZACIÓN CON OPTUNA
# ══════════════════════════════════════════════════════════════
elif paso == 8:
    if st.session_state.X_train is None:
        st.warning("⚠️ Completa los pasos anteriores.")
    else:
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("⚙️ Optimización de Hiperparámetros con OPTUNA")

        best_name = st.session_state.best_model_name
        st.info(f"Se optimizará el mejor modelo base: **{best_name}**")

        n_trials = st.slider("Número de trials", 10, 100, value=30, step=5)

        preprocessor = st.session_state.preprocessor
        X_train = st.session_state.X_train
        X_test = st.session_state.X_test
        y_train = st.session_state.y_train
        y_test = st.session_state.y_test
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

        X_train_proc = preprocessor.fit_transform(X_train)

        def get_objective(model_name):
            def objective(trial):
                if model_name == "Decision Tree":
                    params = {
                        "max_depth": trial.suggest_int("max_depth", 2, 30),
                        "min_samples_split": trial.suggest_int("min_samples_split", 2, 50),
                        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 30),
                        "criterion": trial.suggest_categorical("criterion", ["gini", "entropy"]),
                        "class_weight": "balanced",
                        "random_state": 42,
                    }
                    model = DecisionTreeClassifier(**params)
                elif model_name == "KNN":
                    params = {
                        "n_neighbors": trial.suggest_int("n_neighbors", 3, 30),
                        "weights": trial.suggest_categorical("weights", ["uniform", "distance"]),
                        "metric": trial.suggest_categorical("metric", ["minkowski", "euclidean", "manhattan"]),
                        "p": trial.suggest_int("p", 1, 3),
                    }
                    model = KNeighborsClassifier(**params)
                elif model_name == "SVM":
                    params = {
                        "C": trial.suggest_float("C", 0.01, 100, log=True),
                        "kernel": trial.suggest_categorical("kernel", ["rbf", "poly", "sigmoid"]),
                        "gamma": trial.suggest_float("gamma", 0.001, 10, log=True),
                        "class_weight": "balanced",
                        "probability": True,
                        "random_state": 42,
                    }
                    model = SVC(**params)
                elif model_name == "Random Forest":
                    params = {
                        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
                        "max_depth": trial.suggest_int("max_depth", 3, 30),
                        "min_samples_split": trial.suggest_int("min_samples_split", 2, 30),
                        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20),
                        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
                        "class_weight": "balanced",
                        "random_state": 42,
                        "n_jobs": -1,
                    }
                    model = RandomForestClassifier(**params)
                elif model_name == "LightGBM":
                    params = {
                        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
                        "max_depth": trial.suggest_int("max_depth", 3, 25),
                        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
                        "num_leaves": trial.suggest_int("num_leaves", 10, 150),
                        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
                        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
                        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
                        "reg_alpha": trial.suggest_float("reg_alpha", 1e-6, 10, log=True),
                        "reg_lambda": trial.suggest_float("reg_lambda", 1e-6, 10, log=True),
                        "class_weight": "balanced",
                        "random_state": 42,
                        "verbose": -1,
                        "n_jobs": -1,
                    }
                    model = lgb.LGBMClassifier(**params)
                else:
                    return 0

                scores = cross_val_score(model, X_train_proc, y_train, cv=cv, scoring="accuracy")
                return scores.mean()
            return objective

        if st.button("🚀 Ejecutar Optimización", type="primary", use_container_width=True):
            study = optuna.create_study(direction="maximize", sampler=TPESampler(seed=42))
            study.optimize(get_objective(best_name), n_trials=n_trials, show_progress_bar=False)
            st.session_state.optuna_study = study
            st.session_state.optuna_params = study.best_params

        if st.session_state.optuna_study is not None:
            study = st.session_state.optuna_study
            best_params = study.best_params

            col_a, col_b = st.columns(2)
            with col_a:
                st.markdown(f"**Mejor Accuracy CV:** `{study.best_value:.4f}`")
                st.markdown("**Mejores hiperparámetros:**")
                for k, v in best_params.items():
                    st.markdown(f"- `{k}`: {v}")
            with col_b:
                # Historial de optimización
                fig_opt, ax_opt = plt.subplots(figsize=(8, 5))
                trials_df = study.trials_dataframe()
                ax_opt.plot(trials_df["number"], trials_df["value"],
                           color=C_ACCENT, alpha=0.6, linewidth=1)
                ax_opt.scatter(trials_df["number"], trials_df["value"],
                              color=C_ACCENT, s=20, zorder=5)
                ax_opt.axhline(study.best_value, color=C_ACCENT2, linestyle="--",
                              linewidth=1.5, label=f"Best: {study.best_value:.4f}")
                ax_opt.set_xlabel("Trial", color=C_TEXT)
                ax_opt.set_ylabel("Accuracy CV", color=C_TEXT)
                ax_opt.set_title("Historial de Optimización", color=C_TEXT, fontweight="bold")
                ax_opt.set_facecolor(C_BG)
                fig_opt.patch.set_facecolor(C_CARD)
                ax_opt.legend(facecolor=C_CARD, edgecolor=C_BORDER, labelcolor=C_TEXT)
                ax_opt.spines[:].set_color(C_BORDER)
                ax_opt.tick_params(colors=C_MUTED)
                plt.tight_layout()
                st.pyplot(fig_opt)
                plt.close(fig_opt)

            # Construir pipeline optimizado
            if best_name == "Decision Tree":
                opt_model = DecisionTreeClassifier(**best_params, random_state=42, class_weight="balanced")
            elif best_name == "KNN":
                opt_model = KNeighborsClassifier(**best_params)
            elif best_name == "SVM":
                opt_model = SVC(**best_params, probability=True, random_state=42, class_weight="balanced")
            elif best_name == "Random Forest":
                opt_model = RandomForestClassifier(**best_params, random_state=42, class_weight="balanced", n_jobs=-1)
            elif best_name == "LightGBM":
                opt_model = lgb.LGBMClassifier(**best_params, random_state=42, class_weight="balanced", verbose=-1, n_jobs=-1)

            opt_pipe = Pipeline([("preprocessor", preprocessor), ("model", opt_model)])
            opt_pipe.fit(X_train, y_train)
            st.session_state.optimized_pipeline = opt_pipe
            st.session_state.optuna_model = opt_model

            # Comparación antes/después
            y_test = st.session_state.y_test
            base_res = st.session_state.base_results[st.session_state.base_results["Modelo"] == best_name].iloc[0]
            y_pred_opt = opt_pipe.predict(X_test)
            opt_acc = accuracy_score(y_test, y_pred_opt)
            opt_f1 = f1_score(y_test, y_pred_opt, average="weighted")

            comp_df = pd.DataFrame({
                "Métrica": ["Accuracy CV", "Accuracy Test", "F1 Test"],
                "Base": [base_res["Accuracy CV Mean"], base_res["Accuracy Test"], base_res["F1 Test"]],
                "OPTUNA": [study.best_value, opt_acc, opt_f1],
                "Diferencia": [
                    study.best_value - base_res["Accuracy CV Mean"],
                    opt_acc - base_res["Accuracy Test"],
                    opt_f1 - base_res["F1 Test"],
                ],
            })
            st.markdown("**Comparación Base vs OPTUNA:**")
            st.dataframe(style_df(comp_df.round(4)), use_container_width=True)

            mejora = opt_acc - base_res["Accuracy Test"]
            if mejora > 0:
                st.success(f"✅ OPTUNA mejoró el Accuracy Test en **{mejora:.2%}**")
            else:
                st.info(f"ℹ️ OPTUNA no mejoró significativamente el Accuracy Test (diferencia: {mejora:.4f})")

            # Importancia de hiperparámetros
            if hasattr(study, "trials"):
                try:
                    fig_imp, ax_imp = plt.subplots(figsize=(8, 5))
                    optuna.visualization.matplotlib.plot_param_importances(study, ax=ax_imp)
                    ax_imp.set_facecolor(C_BG)
                    fig_imp.patch.set_facecolor(C_CARD)
                    ax_imp.tick_params(colors=C_MUTED, labelsize=9)
                    ax_imp.set_title("Importancia de Hiperparámetros", color=C_TEXT, fontweight="bold")
                    for text in ax_imp.get_xticklabels() + ax_imp.get_yticklabels():
                        text.set_color(C_TEXT)
                    plt.tight_layout()
                    st.pyplot(fig_imp)
                    plt.close(fig_imp)
                except Exception:
                    pass

        st.markdown("</div>", unsafe_allow_html=True)

        if st.session_state.optimized_pipeline is not None:
            if st.button("Continuar a Ajuste de Thresholds →", type="primary", use_container_width=True):
                st.session_state.step = 9
                st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 9: AJUSTE DE THRESHOLDS
# ══════════════════════════════════════════════════════════════
elif paso == 9:
    if st.session_state.optimized_pipeline is None:
        st.warning("⚠️ Completa la optimización OPTUNA primero.")
    else:
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("🎚️ Ajuste de Threshold de Clasificación")

        pipe = st.session_state.optimized_pipeline
        X_test = st.session_state.X_test
        y_test = st.session_state.y_test

        # Solo para clasificación binaria
        n_classes = len(np.unique(y_test))
        if n_classes == 2:
            y_proba = pipe.predict_proba(X_test)[:, 1]

            # Curva ROC
            fpr, tpr, roc_thresholds = roc_curve(y_test, y_proba)
            roc_auc = auc(fpr, tpr)

            fig, axes = plt.subplots(1, 2, figsize=(14, 5))

            # ROC
            ax = axes[0]
            ax.plot(fpr, tpr, color=C_ACCENT, linewidth=2, label=f"AUC = {roc_auc:.4f}")
            ax.plot([0, 1], [0, 1], color=C_MUTED, linestyle="--", linewidth=1)
            ax.fill_between(fpr, tpr, alpha=0.15, color=C_ACCENT)
            ax.set_xlabel("Tasa de Falsos Positivos (FPR)", color=C_TEXT)
            ax.set_ylabel("Tasa de Verdaderos Positivos (TPR)", color=C_TEXT)
            ax.set_title("Curva ROC", color=C_TEXT, fontweight="bold")
            ax.legend(facecolor=C_CARD, edgecolor=C_BORDER, labelcolor=C_TEXT)
            ax.set_facecolor(C_BG)
            ax.spines[:].set_color(C_BORDER)
            ax.tick_params(colors=C_MUTED)

            # Threshold vs métricas
            ax2 = axes[1]
            thresholds = np.arange(0.05, 1.0, 0.05)
            accs, f1s, precs, recs = [], [], [], []
            for t in thresholds:
                y_pred_t = (y_proba >= t).astype(int)
                accs.append(accuracy_score(y_test, y_pred_t))
                f1s.append(f1_score(y_test, y_pred_t, zero_division=0))
                tp = np.sum((y_pred_t == 1) & (y_test == 1))
                fp = np.sum((y_pred_t == 1) & (y_test == 0))
                fn = np.sum((y_pred_t == 0) & (y_test == 1))
                precs.append(tp / (tp + fp) if (tp + fp) > 0 else 0)
                recs.append(tp / (tp + fn) if (tp + fn) > 0 else 0)

            ax2.plot(thresholds, accs, color=C_ACCENT, linewidth=2, label="Accuracy")
            ax2.plot(thresholds, f1s, color=C_ACCENT2, linewidth=2, label="F1")
            ax2.plot(thresholds, precs, color="#8B5CF6", linewidth=1.5, label="Precisión", linestyle="--")
            ax2.plot(thresholds, recs, color="#EC4899", linewidth=1.5, label="Recall", linestyle="--")

            # Youden's J
            j_scores = tpr - fpr
            best_j_idx = np.argmax(j_scores)
            best_thresh = roc_thresholds[best_j_idx]
            ax2.axvline(best_thresh, color=C_DANGER, linestyle=":", linewidth=1.5,
                       label=f"Óptimo (J) = {best_thresh:.3f}")

            ax2.set_xlabel("Threshold", color=C_TEXT)
            ax2.set_ylabel("Score", color=C_TEXT)
            ax2.set_title("Comportamiento del Modelo por Threshold", color=C_TEXT, fontweight="bold")
            ax2.legend(facecolor=C_CARD, edgecolor=C_BORDER, labelcolor=C_TEXT, fontsize=8)
            ax2.set_facecolor(C_BG)
            ax2.spines[:].set_color(C_BORDER)
            ax2.tick_params(colors=C_MUTED)
            ax2.set_ylim(0, 1.1)

            fig.patch.set_facecolor(C_CARD)
            plt.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

            # Slider de threshold
            selected_t = st.slider(
                "Selecciona un threshold",
                min_value=0.05, max_value=0.95, value=float(best_thresh), step=0.01
            )
            st.session_state.threshold = selected_t

            y_pred_t = (y_proba >= selected_t).astype(int)
            cm = confusion_matrix(y_test, y_pred_t)
            acc_t = accuracy_score(y_test, y_pred_t)
            f1_t = f1_score(y_test, y_pred_t, zero_division=0)

            col_a, col_b, col_c = st.columns(3)
            col_a.metric("Accuracy", f"{acc_t:.4f}")
            col_b.metric("F1 Score", f"{f1_t:.4f}")
            col_c.metric("Threshold", f"{selected_t:.2f}")

            fig_cm, ax_cm = plt.subplots(figsize=(5, 4))
            sns.heatmap(cm, annot=True, fmt="d", cmap="Greens", ax=ax_cm,
                        linewidths=0.5, linecolor=C_BORDER, annot_kws={"size": 14, "color": C_TEXT})
            ax_cm.set_xlabel("Predicho", color=C_TEXT)
            ax_cm.set_ylabel("Real", color=C_TEXT)
            ax_cm.set_title(f"Matriz de Confusión (t={selected_t:.2f})", color=C_TEXT, fontweight="bold")
            ax_cm.set_facecolor(C_BG)
            fig_cm.patch.set_facecolor(C_CARD)
            ax_cm.tick_params(colors=C_MUTED)
            plt.tight_layout()
            st.pyplot(fig_cm)
            plt.close(fig_cm)

            st.markdown(f"""
            <div class='interpretacion'>
            <strong>Análisis del threshold:</strong><br>
            El índice de Youden sugiere un threshold óptimo de <strong>{best_thresh:.3f}</strong>.
            Con el threshold seleccionado de <strong>{selected_t:.2f}</strong>, el modelo alcanza
            Accuracy = <strong>{acc_t:.4f}</strong> y F1 = <strong>{f1_t:.4f}</strong>.
            {'Un threshold bajo aumenta el recall pero reduce la precisión.' if selected_t < 0.4 else 'Un threshold alto aumenta la precisión pero reduce el recall.' if selected_t > 0.6 else 'El threshold está en un rango equilibrado.'}
            </div>
            """, unsafe_allow_html=True)
        else:
            st.warning("El ajuste de thresholds está diseñado para clasificación binaria. Tu target tiene "
                       f"{n_classes} clases. Se usará el threshold por defecto (argmax).")

        st.markdown("</div>", unsafe_allow_html=True)

        if st.button("Continuar a Análisis de Overfitting →", type="primary", use_container_width=True):
            st.session_state.step = 10
            st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 10: ANÁLISIS DE OVERFITTING
# ══════════════════════════════════════════════════════════════
elif paso == 10:
    if st.session_state.X_train is None:
        st.warning("⚠️ Completa los pasos anteriores.")
    else:
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("📈 Análisis de Overfitting — Profundidad vs F1")

        preprocessor = st.session_state.preprocessor
        X_train = st.session_state.X_train
        X_test = st.session_state.X_test
        y_train = st.session_state.y_train
        y_test = st.session_state.y_test

        X_train_p = preprocessor.fit_transform(X_train)
        X_test_p = preprocessor.transform(X_test)

        max_depths = range(1, 31)
        f1_train_list, f1_test_list = [], []
        avg = "weighted" if len(np.unique(y_train)) > 2 else "binary"

        for d in max_depths:
            dt = DecisionTreeClassifier(max_depth=d, random_state=42, class_weight="balanced")
            dt.fit(X_train_p, y_train)
            f1_train_list.append(f1_score(y_train, dt.predict(X_train_p), average=avg))
            f1_test_list.append(f1_score(y_test, dt.predict(X_test_p), average=avg))

        fig, ax = plt.subplots(figsize=(12, 6))
        ax.plot(list(max_depths), f1_train_list, color=C_ACCENT, linewidth=2.5,
                marker="o", markersize=5, label="Train F1", zorder=5)
        ax.plot(list(max_depths), f1_test_list, color=C_ACCENT2, linewidth=2.5,
                marker="s", markersize=5, label="Test F1", zorder=5)

        # Encontrar punto óptimo
        optimal_idx = np.argmax(f1_test_list)
        optimal_depth = list(max_depths)[optimal_idx]
        ax.axvline(optimal_depth, color=C_DANGER, linestyle="--", linewidth=1.5,
                   label=f"Óptimo: depth={optimal_depth} (F1={f1_test_list[optimal_idx]:.4f})")

        # Rellenar zona de overfitting
        if optimal_idx < len(max_depths) - 1:
            ax.axvspan(optimal_depth, 30, alpha=0.1, color=C_DANGER, label="Zona de Overfitting")

        # Rellenar zona de underfitting
        if optimal_idx > 0:
            ax.axvspan(1, optimal_depth, alpha=0.08, color="#3B82F6", label="Zona de Underfitting")

        # Anotar brecha
        gap = f1_train_list[-1] - f1_test_list[-1]
        ax.annotate(f"Brecha: {gap:.3f}",
                    xy=(30, (f1_train_list[-1] + f1_test_list[-1])/2),
                    fontsize=11, color=C_DANGER, fontweight="bold",
                    ha="right")

        ax.set_xlabel("Profundidad Máxima (max_depth)", color=C_TEXT, fontsize=12)
        ax.set_ylabel("F1 Score", color=C_TEXT, fontsize=12)
        ax.set_title("Overfitting: Decision Tree — Profundidad vs F1 (Train vs Test)",
                     color=C_TEXT, fontsize=13, fontweight="bold")
        ax.legend(facecolor=C_CARD, edgecolor=C_BORDER, labelcolor=C_TEXT, fontsize=9, loc="lower right")
        ax.set_facecolor(C_BG)
        fig.patch.set_facecolor(C_CARD)
        ax.spines[:].set_color(C_BORDER)
        ax.tick_params(colors=C_MUTED)
        ax.set_xticks(list(max_depths))
        ax.grid(axis="y", alpha=0.15, color=C_MUTED)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

        # Interpretación
        gap_final = f1_train_list[-1] - f1_test_list[-1]
        if gap_final > 0.15:
            overfit_text = "🔴 <strong>Overfitting severo</strong>: La brecha Train-Test es grande, el modelo memoriza patrones del entrenamiento que no generalizan."
        elif gap_final > 0.05:
            overfit_text = "🟡 <strong>Overfitting moderado</strong>: Existe una brecha noticeable pero controlable."
        else:
            overfit_text = "🟢 <strong>Overfitting mínimo</strong>: El modelo generaliza bien."

        overfit_text += f" La profundidad óptima es <strong>{optimal_depth}</strong> con F1 Test = <strong>{f1_test_list[optimal_idx]:.4f}</strong>. "
        overfit_text += f"A profundidad máxima (30), el F1 Train sube a {f1_train_list[-1]:.4f} pero el F1 Test cae a {f1_test_list[-1]:.4f}, "
        overfit_text += "confirmando que mayor complejidad no implica mejor desempeño."

        st.markdown(f"<div class='interpretacion'>{overfit_text}</div>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
        st.subheader("🤖 Análisis de IA (Overfitting)")
        if st.button("Evaluar Generalización con el Agente", key="btn_agent_overfit"):
            with st.spinner("El Agente está analizando las curvas de Train y Test..."):
                prompt = (
                    "Actúa como un Data Scientist. Observa estos resultados de validación (Train F1 vs Test F1) para diferentes profundidades de árbol.\n"
                    f"Profundidad óptima encontrada: {optimal_depth} con F1 Test de {f1_test_list[optimal_idx]:.4f}.\n"
                    f"A profundidad máxima (30): F1 Train = {f1_train_list[-1]:.4f}, F1 Test = {f1_test_list[-1]:.4f}\n"
                    "Explícale al usuario de forma sencilla qué es el overfitting basándote en estos números descubiertos y confirma si su modelo generaliza bien."
                )
                respuesta = llm_agent_analyze(prompt)
                st.markdown("### 💡 Análisis del Agente")
                st.info(respuesta)
        st.markdown("</div>", unsafe_allow_html=True)

        if st.button("Continuar a SHAP/LIME →", type="primary", use_container_width=True):
            st.session_state.step = 11
            st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 11: EXPLICABILIDAD SHAP + LIME
# ══════════════════════════════════════════════════════════════
elif paso == 11:
    if st.session_state.optimized_pipeline is None:
        st.warning("⚠️ Completa los pasos anteriores.")
    else:
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("🔬 Explicabilidad del Modelo")

        pipe = st.session_state.optimized_pipeline
        X_train = st.session_state.X_train
        X_test = st.session_state.X_test
        y_test = st.session_state.y_test
        preprocessor = st.session_state.preprocessor
        model = pipe.named_steps["model"]
        feature_names = st.session_state.num_cols + st.session_state.cat_cols

        X_train_p = preprocessor.fit_transform(X_train)
        X_test_p = preprocessor.transform(X_test)

        # ── SHAP GLOBAL ──
        st.markdown("### SHAP — Explicabilidad Global")
        with st.spinner("Calculando valores SHAP..."):
            try:
                if isinstance(model, (DecisionTreeClassifier, RandomForestClassifier, lgb.LGBMClassifier)):
                    explainer_shap = shap.TreeExplainer(model)
                else:
                    explainer_shap = shap.KernelExplainer(model.predict_proba, X_train_p[:100])
                shap_values = explainer_shap.shap_values(X_test_p[:200])
            except Exception as e:
                st.error(f"Error con SHAP: {e}")
                shap_values = None

        if shap_values is not None:
            # Calcular importancias de forma segura independientemente del formato de SHAP
            shap_array = np.array(shap_values)

            # Encontrar cuál es el eje de features (buscando la dimensión correcta)
            n_shap_features = X_test_p.shape[1]
            feature_axis = None
            for i, dim in enumerate(shap_array.shape):
                if dim == n_shap_features:
                    feature_axis = i
                    break

            if feature_axis is not None:
                # Promediar el valor absoluto sobre todos los ejes MENOS el de features
                axes_to_mean = tuple(i for i in range(shap_array.ndim) if i != feature_axis)
                mean_abs_shap = np.mean(np.abs(shap_array), axis=axes_to_mean)
            else:
                # Fallback por si algo sale muy mal
                mean_abs_shap = np.mean(np.abs(shap_array), axis=0).flatten()[:n_shap_features]

            # Asegurar que el resultado final sea de 1 sola dimensión
            mean_abs_shap = mean_abs_shap.flatten()

            # Ajustar nombres de features al tamaño real
            if len(feature_names) >= len(mean_abs_shap):
                actual_features = feature_names[:len(mean_abs_shap)]
            else:
                actual_features = [f"Feature_{i}" for i in range(len(mean_abs_shap))]

            # Feature importance bar plot
            order = np.argsort(mean_abs_shap)[::-1]
            colors_bar = [C_ACCENT if i < 5 else C_MUTED for i in range(len(order))]

            fig_bar, ax_bar = plt.subplots(figsize=(10, max(6, len(actual_features)*0.4)))
            ax_bar.barh(range(len(order)), mean_abs_shap[order], color=colors_bar, edgecolor="none", height=0.7)
            ax_bar.set_yticks(range(len(order)))
            labels = [actual_features[i] for i in order]
            ax_bar.set_yticklabels(labels, color=C_TEXT, fontsize=9)
            ax_bar.invert_yaxis()
            ax_bar.set_xlabel("Mean |SHAP value|", color=C_TEXT, fontsize=11)
            ax_bar.set_title("SHAP — Importancia Global de Features", color=C_TEXT, fontweight="bold")
            ax_bar.set_facecolor(C_BG)
            fig_bar.patch.set_facecolor(C_CARD)
            ax_bar.spines[:].set_color(C_BORDER)
            ax_bar.tick_params(colors=C_MUTED)
            plt.tight_layout()
            st.pyplot(fig_bar)
            plt.close(fig_bar)

            # Summary plot (beeswarm) - usamos los valores originales de shap_values
            try:
                fig_bee = plt.figure(figsize=(10, max(6, len(actual_features)*0.4)))
                # Si es multiclase, shap.summary_plot espera la lista original
                shap.summary_plot(shap_values, X_test_p[:200],
                                  feature_names=actual_features,
                                  show=False, max_display=min(15, len(actual_features)))
                fig_bee.patch.set_facecolor(C_CARD)
                ax_bee = fig_bee.axes[0]
                ax_bee.set_facecolor(C_BG)
                ax_bee.tick_params(colors=C_TEXT, labelsize=9)
                ax_bee.xaxis.label.set_color(C_TEXT)
                for text in ax_bee.get_yticklabels():
                    text.set_color(C_TEXT)
                plt.tight_layout()
                st.pyplot(fig_bee)
                plt.close(fig_bee)
            except Exception:
                st.info("No se pudo generar el beeswarm plot (común en modelos multiclase).")

            # Interpretación
            top5_idx = order[:5]
            top5_names = [actual_features[i] for i in top5_idx]
            st.markdown(f"""
            <div class='interpretacion'>
            <strong>Interpretación SHAP Global:</strong><br>
            Las 5 variables más influyentes son: <strong>{', '.join(top5_names)}</strong>.<br>
            <strong>{top5_names[0]}</strong> es la variable con mayor impacto en las predicciones,
            con un valor medio de importancia |SHAP| de {mean_abs_shap[order[0]]:.4f}.
            Las variables con menor impacto podrían ser candidatas a eliminación en futuras iteraciones.
            </div>
            """, unsafe_allow_html=True)

        st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
        st.subheader("🤖 Análisis de IA (SHAP)")
        if st.button("Interpretar Importancia con el Agente", key="btn_agent_shap"):
            with st.spinner("El Agente está interpretando los factores determinantes..."):
                prompt = (
                    "Actúa como un experto en explicabilidad de modelos de IA (XAI). Te paso las 5 variables más importantes encontradas por SHAP:\n"
                    f"{', '.join(top5_names)}\n"
                    "Redacta un párrafo corto y divulgativo orientado al negocio sobre lo que implica que estas variables sean las que más determinan las decisiones."
                )
                if st.session_state.get("metadata_txt"):
                    prompt += f"\n\nContexto extra proporcionado por el usuario (Diccionario de negocio):\n{st.session_state.metadata_txt}"

                respuesta = llm_agent_analyze(prompt)
                st.markdown("### 💡 Visión del Negocio")
                st.info(respuesta)
        st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("</div>", unsafe_allow_html=True)

        # ── LIME LOCAL ──
        st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
        st.markdown("### LIME — Explicabilidad Local")
        st.caption("Selecciona una instancia del conjunto de test para explicar su predicción individual.")

        idx_inst = st.slider("Índice de instancia (test)", 0, min(49, len(X_test)-1), value=0)

        with st.spinner("Generando explicación LIME..."):
            try:
                lime_exp = lime.lime_tabular.LimeTabularExplainer(
                    X_train_p,
                    feature_names=feature_names,
                    class_names=[str(c) for c in st.session_state.label_encoder.classes_],
                    mode="classification",
                    random_state=42,
                )
                explanation = lime_exp.explain_instance(X_test_p[idx_inst], model.predict_proba, num_features=10)

                # Mostrar en Streamlit
                fig_lime = explanation.as_pyplot_figure()
                fig_lime.patch.set_facecolor(C_CARD)
                ax_lime = fig_lime.axes[0]
                ax_lime.set_facecolor(C_BG)
                ax_lime.tick_params(colors=C_TEXT, labelsize=9)
                for text in ax_lime.get_yticklabels() + ax_lime.get_xticklabels():
                    text.set_color(C_TEXT)
                ax_lime.set_title("LIME — Explicación Local", color=C_TEXT, fontweight="bold")
                plt.tight_layout()
                st.pyplot(fig_lime)
                plt.close(fig_lime)

                # Predicción real vs predicha
                y_real = st.session_state.label_encoder.inverse_transform([y_test[idx_inst]])[0]
                y_proba = model.predict_proba(X_test_p[idx_inst].reshape(1, -1))
                y_pred_class = st.session_state.label_encoder.inverse_transform([np.argmax(y_proba)])[0]
                confianza = np.max(y_proba) * 100

                st.markdown(f"""
                <div class='interpretacion'>
                <strong>Explicación LIME local:</strong><br>
                Instancia #{idx_inst}: Clase real = <strong>{y_real}</strong>,
                Clase predicha = <strong>{y_pred_class}</strong> (confianza: {confianza:.1f}%).<br>
                Las características en verde empujan la predicción hacia la clase predicha,
                mientras que las rojas la alejan. Las barras más largas indican mayor influencia.
                </div>
                """, unsafe_allow_html=True)

                # Tabla LIME
                lime_list = explanation.as_list()
                lime_df = pd.DataFrame(lime_list, columns=["Condición", "Peso SHAP Local"])
                lime_df = lime_df.sort_values("Peso SHAP Local", ascending=False)
                st.dataframe(style_df(lime_df.round(4)), use_container_width=True, height=350)
            except Exception as e:
                st.error(f"Error con LIME: {e}")

        st.markdown("</div>", unsafe_allow_html=True)

        if st.button("Continuar a Descarga del Modelo →", type="primary", use_container_width=True):
            st.session_state.step = 12
            st.rerun()

# ══════════════════════════════════════════════════════════════
# PASO 12: DESCARGA DEL MODELO
# ══════════════════════════════════════════════════════════════
elif paso == 12:
    if st.session_state.optimized_pipeline is None:
        st.warning("⚠️ Completa los pasos anteriores.")
    else:
        st.markdown("<div class='card-accent'>", unsafe_allow_html=True)
        st.subheader("💾 Descarga del Modelo Entrenado")

        pipe = st.session_state.optimized_pipeline
        X_test = st.session_state.X_test
        y_test = st.session_state.y_test
        y_pred = pipe.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")

        col_a, col_b, col_c = st.columns(3)
        col_a.metric("Modelo Final", st.session_state.best_model_name)
        col_b.metric("Accuracy", f"{acc:.4f}")
        col_c.metric("F1 Score", f"{f1:.4f}")

        # Guardar modelo + metadatos
        model_data = {
            "pipeline": pipe,
            "label_encoder": st.session_state.label_encoder,
            "feature_names": st.session_state.num_cols + st.session_state.cat_cols,
            "target_col": st.session_state.target_col,
            "num_cols": st.session_state.num_cols,
            "cat_cols": st.session_state.cat_cols,
            "optuna_params": st.session_state.optuna_params,
            "threshold": st.session_state.threshold,
            "accuracy": acc,
            "f1_score": f1,
        }
        buffer = io.BytesIO()
        joblib.dump(model_data, buffer)
        buffer.seek(0)

        st.markdown("""
        <div class='interpretacion'>
        <strong>Instrucciones de uso:</strong><br><br>
        1. Descarga el archivo <code>.pkl</code> usando el botón de abajo.<br>
        2. Para cargar el modelo en Python:<br>
        <code style='background:#0B0F19;padding:8px;border-radius:4px;display:block;margin:8px 0'>
        import joblib<br>
        model_data = joblib.load("modelo_entrenado.pkl")<br>
        pipeline = model_data["pipeline"]<br>
        label_encoder = model_data["label_encoder"]<br>
        predicciones = pipeline.predict(nuevos_datos)<br>
        clases = label_encoder.inverse_transform(predicciones)
        </code>
        3. El pipeline incluye preprocesamiento (imputación + escalado + encoding) y el modelo optimizado.
        </div>
        """, unsafe_allow_html=True)

        st.download_button(
            label="⬇️ Descargar Modelo Entrenado (.pkl)",
            data=buffer,
            file_name="ml_agent_pro_modelo.pkl",
            mime="application/octet-stream",
            use_container_width=True,
        )

        # También ofrecer código de predicción
        st.markdown("---")
        st.subheader("📋 Código de Predicción")
        feature_names = model_data["feature_names"]
        code = f"""
import pandas as pd
import joblib

# Cargar modelo
data = joblib.load("ml_agent_pro_modelo.pkl")
pipe = data["pipeline"]
le = data["label_encoder"]
features = {feature_names}

# Crear DataFrame con nuevos datos (misma estructura)
nuevos_datos = pd.DataFrame({{
    # Ejemplo: reemplaza con tus datos reales
    "{feature_names[0] if feature_names else 'col'}": [0],
}})

# Asegurar que todas las columnas estén presentes
for col in features:
    if col not in nuevos_datos.columns:
        nuevos_datos[col] = 0
nuevos_datos = nuevos_datos[features]

# Predecir
pred = pipe.predict(nuevos_datos)
clases = le.inverse_transform(pred)
prob = pipe.predict_proba(nuevos_datos)

print(f"Clase predicha: {{clases[0]}}")
print(f"Probabilidades: {{dict(zip(le.classes_, prob[0]))}}")
"""
        st.code(code, language="python")

        st.markdown("</div>", unsafe_allow_html=True)

        # Resumen final
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.subheader("🏆 Resumen del Pipeline Completo")
        resumen_data = {
            "Etapa": [
                "Dataset", "Target", "Features finales", "Imputación",
                "División", "Mejor modelo base", "OPTUNA",
                "Threshold óptimo", "Accuracy final", "F1 final", "Explicabilidad"
            ],
            "Resultado": [
                f"{st.session_state.df.shape[0]:,} filas × {st.session_state.df.shape[1]} columnas",
                st.session_state.target_col,
                len(feature_names),
                "Aplicada según tipo de variable",
                "70% train / 30% test",
                st.session_state.best_model_name,
                str(st.session_state.optuna_params.get('max_depth', 'N/A')) if st.session_state.optuna_params else 'N/A',
                f"{st.session_state.threshold:.2f}",
                f"{acc:.4f}",
                f"{f1:.4f}",
                "SHAP global + LIME local"
            ]
        }
        st.dataframe(style_df(pd.DataFrame(resumen_data)), use_container_width=True, height=450)
        st.markdown("</div>", unsafe_allow_html=True)

# ── Footer ───────────────────────────────────────────────────
st.markdown("""
<div style='
    text-align:center;
    padding:32px 24px 24px;
    border-top:1px solid #1E293B;
    margin-top:40px;
'>
    <p style='color:#10B981;font-size:0.95rem;font-weight:600;margin-bottom:6px;letter-spacing:0.05em'>
        🤖 ML Agent Pro
    </p>
    <p style='color:#94A3B8;font-size:0.82rem;margin-bottom:16px'>
        Agente Inteligente de Machine Learning · Pipeline automatizado de clasificación con explicabilidad
    </p>
    <div style='display:inline-flex;gap:24px;align-items:center;justify-content:center;
                background:#131A2B;border:1px solid #1E293B;border-radius:12px;
                padding:12px 28px;margin-bottom:8px'>
        <span style='color:#64748B;font-size:0.78rem;text-transform:uppercase;letter-spacing:0.1em'>Desarrollado por</span>
        <span style='color:#E2E8F0;font-size:0.88rem;font-weight:600'>
            ✦ Yarley Camilo Mejía &nbsp;·&nbsp; Victor Manuel Alzate ✦
        </span>
    </div>
    <p style='color:#334155;font-size:0.75rem;margin-top:10px'>
        Universidad del Quindio · Inteligencia Artificial
    </p>
</div>
""", unsafe_allow_html=True)